// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi5R7B4yQxXLLWLP3-xn-E_LnmttZSN-U',
    appId: '1:737865687285:web:ae9f133d265f53c46ee5bc',
    messagingSenderId: '737865687285',
    projectId: 'flutternotifi-ba59f',
    authDomain: 'flutternotifi-ba59f.firebaseapp.com',
    storageBucket: 'flutternotifi-ba59f.appspot.com',
    measurementId: 'G-N2BF3NDYQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGWeC5gnU8gKYtOV_8Y474_LHF-DxeVQo',
    appId: '1:737865687285:android:7cc0465e55a237d36ee5bc',
    messagingSenderId: '737865687285',
    projectId: 'flutternotifi-ba59f',
    storageBucket: 'flutternotifi-ba59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMT10y0kuYh-uMI1Y_uORYOeawP5e_N8',
    appId: '1:737865687285:ios:3e4536c95940b06d6ee5bc',
    messagingSenderId: '737865687285',
    projectId: 'flutternotifi-ba59f',
    storageBucket: 'flutternotifi-ba59f.appspot.com',
    iosBundleId: 'com.example.demo9july',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuMT10y0kuYh-uMI1Y_uORYOeawP5e_N8',
    appId: '1:737865687285:ios:3e4536c95940b06d6ee5bc',
    messagingSenderId: '737865687285',
    projectId: 'flutternotifi-ba59f',
    storageBucket: 'flutternotifi-ba59f.appspot.com',
    iosBundleId: 'com.example.demo9july',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi5R7B4yQxXLLWLP3-xn-E_LnmttZSN-U',
    appId: '1:737865687285:web:0e70f796a2ed0dbe6ee5bc',
    messagingSenderId: '737865687285',
    projectId: 'flutternotifi-ba59f',
    authDomain: 'flutternotifi-ba59f.firebaseapp.com',
    storageBucket: 'flutternotifi-ba59f.appspot.com',
    measurementId: 'G-3K9M1XK4W3',
  );
}
